### ISSUE TITLE
Manually setting a sequences numbers in the console.

### ISSUE THREAD

**Issue by davidvgus** [thoughtbot/factory_girl#615]
I would like to be able to manually set the sequence number for a factory attribute when I'm in the console.  I figure there is probably good reason why FactoryGirl doesn't let one manually set a sequence number but I'm not advanced enough to know what that reason is.  I wrote a post about what I was trying to do and an easy work around but it seems like such a trivial change I thought I would ask about it.

http://stormy-anchorage-2121.herokuapp.com/blog/2014/02/17/factorygirl-slash-rails-console-sequencing-issue/

**Comment by 3DEsprit** [comment]
Has this been resolved in some way?

I have also run into this scenario, and think it would be a great addition if it doesn't exist somewhere now. I have found myself taking advantage of console for rapid testing analysis. Even simply offering an extra argument to the create_list to offset the sequence would be more than sufficient.

**Comment by nightpool** [comment]
It's been many years, but this is still an issue we're running into. It would be great to be able to use FactoryBot from the console, but we need a way to reset the sequences to avoid conflicts

**Comment by CodeMeister** [comment]
Hi @nightpool,  

This issue has been closed for a few years now.  If you raise a new issue, I'll do a PR to add that functionality. 😃
